version: '3.5'

services:
  api:
    restart: always
    environment:
      - CURRENCY_SLUG=${CURRENCY_SLUG}
      - CURRENCY_SYMBOL=${CURRENCY_SYMBOL}
      - ENV=prod
      - SESSION_TIMEOUT=${SESSION_TIMEOUT}
      - MIN_LENGTH_PWD=${MIN_LENGTH_PWD}
      - MAX_LENGTH_PWD=${MAX_LENGTH_PWD} 
      - DJANGO_DEBUG=${DJANGO_DEBUG} 
      - API_PUBLIC_URL=http://localhost:8000
      - DOLIBARR_PUBLIC_URL=http://localhost:8080
      - BDC_PUBLIC_URL=http://localhost:8001
      - GI_PUBLIC_URL=http://localhost:8002
      - CEL_PUBLIC_URL=http://front:8000
      - EMAIL_NOTIFICATION_GESTION=${EMAIL_NOTIFICATION_GESTION}
      - RAVEN_CONFIG_DSN=http://46498c24303d4b27828e5e47ce927818:6177efcf6d1d47508f1c22332c8dddaf@sentry:9000/2

